version: "3.1"
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=passwordDB
    ports:
      - "3033:3306"
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8080:80"